version: '3.8'
services:
  combined-service:
    build:
      context: .
      dockerfile: Dockerfile.svc
    container_name: combined-services
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: upstage
    ports:
      - "5432:5432"
      - "27017:27017"
      - "1883:1883"
      - "9001:9001"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - mongo_data:/data/db
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mongo/mongod.conf:/etc/mongod.conf  # Mount custom config file
    networks:
      - api-network
  upstage:
    build:
      context: ../
      dockerfile: ./single-container/Dockerfile.app
    container_name: upstage_app
    ports:
      - "3000:3000"
    volumes:
      - ./system/upstage:/app
      -  /home/upstage2/uploads:/usr/app/uploads
    networks:
      - api-network
  
networks:
  api-network:
volumes:
  postgres_data:
  mongo_data:
  mosquitto_data:
  mosquitto_log: