# Certs are handled by nginx, not here.
# This implies an mqtt. domain name to resolve SSL at the nginx layer.

persistence true
persistence_location /var/lib/mosquitto/

listener 1883
protocol mqtt

listener 9001
protocol websockets

http_dir /etc/mosquitto/http
log_type error
log_type warning
#log_type notice
#log_type information
#log_type websockets
#log_type all
#websockets_log_level 255
connection_messages true
log_timestamp true
log_dest stdout
allow_anonymous false
password_file /etc/mosquitto/pw.txt

