services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - /postgresql_data_volume:/data/db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: nas78a98sdfnwkjer2zkjhku
      POSTGRES_USER: postgres
      POSTGRES_DB: upstage
    networks:
     - upstage-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    volumes:
      - /mongodb_data_volume:/data/mongodb
    networks:
    - upstage-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto_data:/mosquitto/data
      - ./../container_scripts/mqtt_server/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./../container_scripts/mqtt_server/pw.txt:/etc/mosquitto/pw.txt
      - ./../container_scripts/mqtt_server/local_mosquitto.conf:/etc/mosquitto/conf.d/local_mosquitto.conf
      - ./../container_scripts/mqtt_server/add_mqtt_cert_crontab.sh:/cron_scipts/add_mqtt_cert_crontab.sh
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
     - upstage-network
    command:
      /bin/sh -c "chmod 0700 /etc/mosquitto/pw.txt &&
      mosquitto_passwd -U /etc/mosquitto/pw.txt && 
      /cron_scripts/add_mqtt_cert_crontab.sh &&
      mosquitto -c /etc/mosquitto/mosquitto.conf"
      #/bin/sh -c "/bin/sh"
    restart: no


  upstage:
    build:
      context: ../
      dockerfile: ./multiple-containers/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./system/upstage:/app
      -  /home/upstage2/uploads:/usr/app/uploads
      - /root/upstage/dashboard/demo:/usr/app/dashboard/demo
    networks:
      - upstage-network

  upstage_event_archive:
    build:
      context: ../
      dockerfile: ./multiple-containers/Dockerfile.upstage_event_archive
    container_name: upstage_event_archive_container
    ports:
      - "83:80"
      - "446:443"
    volumes:
      - ./system/event_archive:/app
    networks:
      - upstage-network

  upstage_email:
    build:
      context: ../
      dockerfile: ./multiple-containers/Dockerfile.upstage_email
    container_name: upstage_email_container
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./system/email:/app
    networks:
      - upstage-network

  upstage_stats:
    build:
      context: ../
      dockerfile: ./multiple-containers/Dockerfile.upstage_stats
    container_name: upstage_stats_container
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - ./system/stats:/app
    networks:
      - upstage-network

networks:
  upstage-network:
volumes:
  data-volume:
  mongo_data:
  mosquitto_data:
