DATABASE_CONNECT = "postgresql"
DATABASE_HOST = "postgres"
DATABASE_PORT = 5432
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "{POSTGRES_PASSWORD}"
DATABASE_NAME = "upstage"

MONGO_DB = "upstage"
MONGO_HOST = "mongodb"
MONGO_PORT = 27017
EVENT_COLLECTION = "events"
MONGODB_COLLECTION_TOKEN = "token"
MONGO_EMAIL_DB = "email"
MONGO_EMAIL_HOST = "mongodb"
MONGO_EMAIL_PORT = 27017

EMAIL_USE_TLS = False
EMAIL_HOST = "{EMAIL_HOST}"
EMAIL_HOST_USER = "{EMAIL_HOST_USER}"
EMAIL_HOST_PASSWORD = "{EMAIL_HOST_PASSWORD}"
EMAIL_PORT = int("{EMAIL_PORT}")
EMAIL_HOST_DISPLAY_NAME = "UpStage Support"
MQTT_BROKER = "mosquitto"
MQTT_PORT = 1883
MQTT_TRANSPORT = "tcp"
MQTT_USER = "admin"
MQTT_PASSWORD = "{MQTT_PASSWORD}"


# payment
STRIPE_KEY = "{STRIPE_KEY}"
STRIPE_PRODUCT_ID = "{STRIPE_PRODUCT_ID}"