DATABASE_CONNECT = "postgresql"
DATABASE_HOST = "{SVC_HOST}"
DATABASE_PORT = 5433
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "{REPLACE_POSTGRES_PASSWORD}"
DATABASE_NAME = "upstage"

MONGO_DB = "upstage"
MONGO_HOST = "{SVC_HOST}"
MONGO_PORT = 27018
MONGO_USER = "admin"
MONGO_PASSWORD = "{REPLACE_MONGO_PASSWORD}"
EVENT_COLLECTION = "events"
MONGODB_COLLECTION_TOKEN = "token"
MONGO_EMAIL_DB = "email"
MONGO_EMAIL_HOST = "mongodb"
MONGO_EMAIL_PORT = 27018
MONGO_EMAIL_PASSWORD = "{REPLACE_MONGO_PASSWORD}"
MONGO_USER = "admin"

EMAIL_USE_TLS = False
EMAIL_HOST = "{EMAIL_HOST}"
EMAIL_HOST_USER = "{EMAIL_HOST_USER}"
EMAIL_HOST_PASSWORD = "{EMAIL_HOST_PASSWORD}"
EMAIL_PORT = int("{EMAIL_PORT}")
EMAIL_HOST_DISPLAY_NAME = "UpStage Support"
MQTT_BROKER = "{SVC_HOST}"
MQTT_PORT = 1884
MQTT_TRANSPORT = "tcp"
MQTT_USER = "admin"
MQTT_PASSWORD = "{REPLACE_MQTT_P_PASSWORD}"


UPLOAD_USER_CONTENT_FOLDER="./uploads"
DEMO_MEDIA_FOLDER="./dashboard/demo"

# payment
STRIPE_KEY = ""
STRIPE_PRODUCT_ID = ""
