DATABASE_CONNECT = "postgresql"
DATABASE_HOST = "localhost"
DATABASE_PORT = 5432
DATABASE_USER = "postgres"
DATABASE_PASSWORD = "postgres"
DATABASE_NAME = "upstage_test"

MONGO_DB = "upstage"
MONGO_HOST = "mongodb"
MONGO_PORT = 27017
EVENT_COLLECTION = "events"
MONGODB_COLLECTION_TOKEN = "token"
MONGO_EMAIL_DB = "email"
MONGO_EMAIL_HOST = "mongodb"
MONGO_EMAIL_PORT = 27017

EMAIL_USE_TLS = False
EMAIL_HOST = "mail.gandi.net"
EMAIL_HOST_USER = "support@upstage.live"
EMAIL_HOST_PASSWORD = "4=Mw-a!xf34+XgGedt*E"
EMAIL_PORT = 465
EMAIL_HOST_DISPLAY_NAME = "UpStage Support"
MQTT_BROKER = "mosquitto"
MQTT_PORT = 1883
MQTT_TRANSPORT = "tcp"
MQTT_USER = "admin"
MQTT_PASSWORD = "908nn4uHZqdJods7"


# payment
STRIPE_KEY = "rk_test_51L1O24LPPLa7BD025HIKU6IvtFrSyeujeIGioUl73rPCkHA02hfqVjztHK0YzDQs7otJDvPzNumXXpz9T6I7EoKT00G6TFurUJ"
STRIPE_PRODUCT_ID = ""

ENV_TYPE = "test"
