version: '3.8'
services:
  standalone_service_container:
    build:
      context: .
      dockerfile: Dockerfile.svc
    container_name: standalone_service_container
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: upstage
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "5433:5432"
      - "27018:27017"
      - "1884:1883"
      - "9002:9001"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - mongo_data:/data/db
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mongo/mongod.conf:/etc/mongod.conf  # Mount custom config file
    networks:
      - api-network
  
networks:
  api-network:
volumes:
  postgres_data:
  mongo_data:
  mosquitto_data:
  mosquitto_log: