services:
  upstage:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_container
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/app
      -  /home/upstage2/uploads:/usr/app/uploads
      - /root/upstage/dashboard/demo:/usr/app/dashboard/demo

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      chmod +x ./startup.sh &&
      ./startup.sh"
    networks:
      - service_containers_upstage-network

  upstage_event_archive:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_event_archive_container
    ports:
      - "83:80"
      - "446:443"
    volumes:
      - ../:/usr/app

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_event_archive"
    networks:
      - service_containers_upstage-network    

  upstage_stats:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_stats_container
    ports:
      - "84:80"
      - "447:443"
    volumes:
      - ../:/usr/app
    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_upstage_stats"
    networks:
      - service_containers_upstage-network   

networks:
  service_containers_upstage-network:
volumes:
  app:
