name: upstage-backend-prod
services:
  upstage_backend:
    build:
      context: ../
      dockerfile: app_containers/Dockerfile
    image: upstage/backend:local
    container_name: upstage_backend
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    ports:
      - "3000:3000"
    #extra_hosts:
    #  - "dev.upstage.live:10.116.0.8"
    volumes:
      - /app_code/alembic:/usr/app/alembic
      - /app_code/src:/usr/app/src
      - /app_code/pyproject.toml:/usr/app/pyproject.toml
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/uploads:/usr/app/uploads
      - /app_code/demo:/usr/app/dashboard/demo
      - /app_code/scripts:/usr/app/scripts
      - /app_code/migration_scripts:/usr/app/migration_scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      ./scripts/start_upstage.sh"
    networks:
      - upstage-network

  upstage_event_archive:
    build:
      context: ../
      dockerfile: app_containers/Dockerfile
    image: upstage/backend:local
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    container_name: upstage_event_archive
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/pyproject.toml:/usr/app/pyproject.toml
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts

    command: >
      /bin/bash -c "
      cd /usr/app &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.run_event_archive"
    networks:
      - upstage-network

  upstage_stats:
    build:
      context: ../
      dockerfile: app_containers/Dockerfile
    image: upstage/backend:local
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    container_name: upstage_stats
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/pyproject.toml:/usr/app/pyproject.toml
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.run_upstage_stats"
    networks:
      - upstage-network

  # For Upstage internal use. Maybe some clients will need this as well.
  # Backups happen on a conventional mounted disk, because all image disks are SSD.
  upstage_backups:
    build:
      context: ../
      dockerfile: app_containers/Dockerfile_backups
    image: upstage/backups:local
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    container_name: upstage_backups
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/pyproject.toml:/usr/app/pyproject.toml
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/uploads:/usr/app/uploads
      - /app_code/scripts:/usr/app/scripts
      - /mnt/backups:/mnt/backups # upstage mounted backup drive
    command: >
      /bin/bash -c "
      cd /usr/app &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.backup_to_local_drive"
    networks:
      - upstage-network

  # For Upstage internal use. Maybe some clients will need this as well.
  upstage_emails:
    build:
      context: ../
      dockerfile: app_containers/Dockerfile
    image: upstage/backend:local
    container_name: upstage_external_email_tokens
    user: "${HOST_UID:-1000}:${HOST_GID:-1000}"
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/pyproject.toml:/usr/app/pyproject.toml
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.run_upstage_email"
    networks:
      - upstage-network

networks:
  upstage-network:
    driver: bridge
    external: true
