services:
  upstage:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_container
    ports:
      - "3000:3000"
    volumes:
      - /app_code/ruff_cache:/usr/app/ruff_cache
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/uploads:/usr/app/uploads
      - /app_code/demo:/usr/app/dashboard/demo
      - /app_code/startup.sh:/usr/app/startup.sh
      - /app_code/alembic.ini:/usr/app/alembic.ini

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r ./requirements.txt &&
      ./startup.sh"
    networks:
      - upstage-network

  upstage_event_archive:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_event_archive_container
    ports:
      - "83:80"
      - "446:443"
    volumes:
      - /app_code/ruff_cache:/usr/app/ruff_cache
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts
      - /app_code/startup.sh:/usr/app/startup.sh
      - /app_code/alembic.ini:/usr/app/alembic.ini

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_event_archive"
    networks:
      - upstage-network    

  upstage_stats:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_stats_container
    ports:
      - "84:80"
      - "447:443"
    volumes:
      - /app_code/ruff_cache:/usr/app/ruff_cache
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts
      - /app_code/startup.sh:/usr/app/startup.sh
      - /app_code/alembic.ini:/usr/app/alembic.ini
    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_upstage_stats"
    networks:
      - upstage-network   

networks:
  upstage-network:
