name: upstage-backend-dev
services:
  upstage_backend_dev:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_backend_dev
    ports:
      - "3001:3000"
    #extra_hosts:
    #  - "dev.upstage.live:10.116.0.8"
    volumes:
      - /app_code_dev/alembic:/usr/app/alembic
      - /app_code_dev/src:/usr/app/src
      - /app_code_dev/pyproject.toml:/usr/app/pyproject.toml
      - /app_code_dev/requirements.txt:/usr/app/requirements.txt
      - /app_code_dev/uploads:/usr/app/uploads
      - /app_code_dev/demo:/usr/app/dashboard/demo
      - /app_code_dev/scripts:/usr/app/scripts
      - /app_code_dev/migration_scripts:/usr/app/migration_scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r ./requirements.txt &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      ./scripts/start_upstage.sh"
    networks:
      - upstage-network-dev

  upstage_event_archive_dev:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_event_archive_dev
    volumes:
      - /app_code_dev/src:/usr/app/src
      - /app_code_dev/pyproject.toml:/usr/app/pyproject.toml
      - /app_code_dev/requirements.txt:/usr/app/requirements.txt
      - /app_code_dev/scripts:/usr/app/scripts

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.run_event_archive"
    networks:
      - upstage-network-dev

  upstage_stats_dev:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_stats_dev
    volumes:
      - /app_code_dev/src:/usr/app/src
      - /app_code_dev/pyproject.toml:/usr/app/pyproject.toml
      - /app_code_dev/requirements.txt:/usr/app/requirements.txt
      - /app_code_dev/scripts:/usr/app/scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      export HARDCODED_HOSTNAME=${HARDCODED_HOSTNAME} &&
      python3 -m scripts.run_upstage_stats"
    networks:
      - upstage-network-dev

networks:
  upstage-network-dev:
    driver: bridge
    external: true
