services:
  upstage:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_container
    ports:
      - "3000:3000"
    volumes:
      - /app_code/alembic:/usr/app/alembic
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/uploads:/usr/app/uploads
      - /app_code/demo:/usr/app/dashboard/demo
      - /app_code/scripts:/usr/app/scripts

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r ./requirements.txt &&
      ./scripts/start_upstage.sh"
    networks:
      - upstage-network

  upstage_event_archive:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_event_archive_container
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts

    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_event_archive"
    networks:
      - upstage-network    

  upstage_stats:
    image: registry.access.redhat.com/ubi9/python-312:latest
    container_name: upstage_stats_container
    volumes:
      - /app_code/src:/usr/app/src
      - /app_code/requirements.txt:/usr/app/requirements.txt
      - /app_code/scripts:/usr/app/scripts
    command: >
      /bin/bash -c "
      cd /usr/app &&
      pip install --upgrade pip &&
      pip install -r requirements.txt &&
      python3 -m scripts.run_upstage_stats"
    networks:
      - upstage-network   

  # For Upstage internal use only.
  #upstage_emails:
  #  image: registry.access.redhat.com/ubi9/python-312:latest
  #  container_name: upstage_external_email_tokens
  #  volumes:
  #    - /app_code/src:/usr/app/src
  #    - /app_code/requirements.txt:/usr/app/requirements.txt
  #    - /app_code/scripts:/usr/app/scripts
  #  command: >
  #    /bin/bash -c "
  #    cd /usr/app &&
  #    pip install --upgrade pip &&
  #    pip install -r requirements.txt &&
  #    python3 -m scripts.run_upstage_email"
  #  networks:
  #    - upstage-network   

networks:
  upstage-network:
