services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    volumes:
      - /postgresql_data_volume:/data/db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: upstage
    networks:
     - upstage-network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27018:27017"
    volumes:
      - /mongodb_data_volume:/data/mongodb
    restart: unless-stopped
    networks:
    - upstage-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      # Auto-change the password in the pw.txt file referenced below:
      - ./mosquitto_data:/mosquitto/data
      - ./../container_scripts/mqtt_server/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - ./../container_scripts/mqtt_server/pw.txt:/etc/mosquitto/pw.txt
      - ./../container_scripts/mqtt_server/local_mosquitto.conf:/etc/mosquitto/conf.d/local_mosquitto.conf
      - ./../container_scripts/mqtt_server/add_mqtt_cert_crontab.sh:/etc/mosquitto/cron/add_mqtt_cert_crontab.sh
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
     - upstage-network
    command:
      /bin/sh -c "chmod 0700 /etc/mosquitto/pw.txt &&
      mosquitto_passwd -U /etc/mosquitto/pw.txt && 
      chown mosquitto:mosquitto /etc/mosquitto/pw.txt &&
      /etc/mosquitto/cron/add_mqtt_cert_crontab.sh &&
      mkdir /etc/http &&
      mosquitto -c /etc/mosquitto/mosquitto.conf"
      #/bin/sh -c "/bin/sh"
    restart: no

networks:
  upstage-network:
volumes:
  postgresql_data_volume:
  mongodb_data_volume:
  mosquitto_data:
